# Configuration

format = """$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$nodejs\
$rust\
$battery\
$time
$username$status$character"""

[username]
style_user = "#0d8cb2"
style_root = "#0d8cb2"
show_always = true
format = "[ $user ](bg:$style fg:#ffffff bold)"

[character]
success_symbol = "[ ](fg:#0d8cb2 bg:#04323f)[](fg:#04323f)"
error_symbol = "[ ](fg:#0d8cb2 bg:bright-red)[](fg:bright-red)"
vicmd_symbol = "[](bold green)"
format = "$symbol "

[status]
style = "#0d8cb2"
format = "[| ](bg:$style fg:bold #ffffff)[$status ](bg:$style fg:bold red)"
disabled = false
