#!/bin/sh

update_widget () {
    sleep 0.02
    [ $XDG_SESSION_DESKTOP = "none+awesome" ] && awesome-client "awesome.emit_signal('signal::brightness')"
}

if [ $1 = "get" ]; then
    brightnessctl i
elif [ $1 = "raise" ]; then
    brightnessctl s +10%
    update_widget
elif [ $1 = "lower" ]; then
    brightnessctl s 10%-
    update_widget
fi
