#!/bin/sh

# color=$(grim -g "$(slurp -p -b '#00000000')" -t ppm - \
#     | convert - -format '%[pixel:p{0,0}]' txt:- )

color=$(hyprpicker --no-fancy --format hex)

wl-copy "$color"

notify-send "Color Picked" "$color\nCopied to clipboard." \
    -a "Color picker" \
    -t 5000
