#!/bin/sh

# Reload hyprland and various services

HYPR=~/.config/hypr/

wallpaper() {
    if [ -f ~/.config/wallpaper-hyprland ]; then
        swaybg -m fill -i ~/.config/wallpaper-hyprland &!
    elif [ -f ~/.config/wallpaper ]; then
        swaybg -m fill -i ~/.config/wallpaper &!
    fi
}

reload_init() {
    wallpaper
    eww -c $HYPR/eww daemon
    eww -c $HYPR/eww open top-panel
    eww -c $HYPR/eww open bg-dashboard
}

reload_default() {
    pkill swaybg
    
    hyprctl reload

    wallpaper
    sleep 0.5
    eww -c $HYPR/eww reload
}

reload_all() {
    pkill -9 waybar
    pkill eww
    pkill swaybg

    hyprctl reload

    wallpaper
    eww -c $HYPR/eww daemon
    eww -c $HYPR/eww open top-panel
    eww -c $HYPR/eww open bg-dashboard
}

if [ "$1" = "all" ]; then
    reload_all
elif [ "$1" = "init" ]; then
    reload_init
else
    reload_default
fi
