#!/bin/sh

# Volume getter/setter

sink=$(pactl get-default-sink)

update_widget () {
    sleep 0.02
    paplay $share/vol-changed.wav
}

if [ $1 = "get" ]; then
    vol=$(pactl get-sink-volume $sink | awk '/Volume/ {print $5}' | sed 's/%//')
    mute=$(pactl get-sink-mute $sink | awk '/Mute/ {print $2}')
    if [ "$mute" = "yes" ]; then
        mute="true"
    else
        mute="false"
    fi
    echo "{\"volume\": $vol, \"mute\": $mute}"
elif [ $1 = "raise" ]; then
    pactl set-sink-volume $sink +5%
    # limit to 100%
    pactl get-sink-volume $sink | grep -q -e '1..\%' && \
        pactl set-sink-volume $sink 100%
    update_widget
elif [ $1 = "lower" ]; then
    pactl set-sink-volume $sink -5%
    update_widget
elif [ $1 = "toggle" ]; then
    pactl set-sink-mute $sink toggle
    update_widget
fi
