#!/bin/sh

shopt -s nullglob globstar
set -e

# Run menu
run () {
    dmenu_run
}


# Logout / Power menu
powermenu () {
    up_time=$(uptime)
    username=$(id -un)

    option_sleep="sleep"
    option_reboot="reboot"
    option_poweroff="poweroff"
    option_lock="lock"
    option_logout="logout"

    declare -a options=(
        $option_sleep
        $option_reboot
        $option_poweroff
        $option_lock
        $option_logout
    )

    choice=$(\
        printf '%s\n' "${options[@]}" | \
        dmenu -i -p "$up_time")

    if [[ $choice == $option_sleep ]]; then
        i3lock -c 101010 && sleep 0.5 && suspend
    elif [[ $choice == $option_reboot ]]; then
        systemctl reboot
    elif [[ $choice == $option_poweroff ]]; then
        systemctl poweroff
    elif [[ $choice == $option_lock ]]; then
        i3lock -c 101010
    elif [[ $choice == $option_logout ]]; then
        loginctl kill-user $username
    fi
}

if [ $1 = "drun" ]; then
    drun $2
elif [ $1 = "run" ]; then
    run $2
elif [ $1 = "power" ]; then
    powermenu
fi

